services:
    jenkins:
        build: ./jenkins/master
        image: yanivomc/jenkins-jb-master:1.0
        container_name: jenkins
        volumes:
          - ./casc_configs/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
          - ./volume/jenkinsmaster:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - '8080:8080'
          - '8081:8080'
          - '50000:50000'
        environment:
          - 'CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml'
          - 'ADMIN_PASSWORD=admin1234'
        networks: 
          - jb

networks: 
  jb: