version: '3.8' # docker compose yml version for docker compose builder
services: # Here we define our architecture services / roles
   nginx: # or web_role  , api_role , db_mysql , db_redis ....
   build:  # Dockerfile to build or use image: to pull from DockerHub (public/private) or git
          context: . # folder where the dockerfile is located
          dockerfile: #[dockerfile-name]
   Image: yanivomc/spring-music:latest
   ports: # Ports we wish to expose source:target
     - 8080:8080
     - 80:80
   volumes: # Which Bind mounts or Volumes to mount source:target
      - type: bind        # Shortsyntax -> ./source:/code
        source: /source
        target: /code
      - type: volume       # Shortsyntax -> logicalVolume01:/var/log
        source: logicalVoloume01
        target: /var/log
   networks: # Define netwroks per service / role
     - db_layer
     - app_layer

networks: # custom configuration per network defined
 db_layer:
 app_layer:

volumes:
 logicalVoloume01:
