apiVersion: v1
kind: Pod
metadata:
  name: volume-app
  labels: 
    app: volume
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - name: app2
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /storage
      name: app-storage    
  volumes:
    - name: app-storage
      hostPath:
        path: /tmp/files
        type: DirectoryOrCreate