apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx
spec:
 containers: 
 - name: nginx1 
   image: nginx:latest 
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080

