# If Values.argoApplication.install is true, install the ArgoCD Application.
{{- if .Values.argoApplication.install }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argoApplication.name }}
  namespace: argocd
spec:
  project: {{ .Values.argoApplication.project }}
  source:
    repoURL: '{{ .Values.argoApplication.repoURL }}'
    path: '{{ .Values.argoApplication.path }}'
    targetRevision: {{ .Values.argoApplication.targetRevision }}
  destination:
    server: {{ .Values.argoApplication.server }}
    namespace: {{ .Values.argoApplication.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.argoApplication.prune }}
      selfHeal: {{ .Values.argoApplication.selfHeal }}
{{- end }}

