apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace:  argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ankitsingh16391/devopshift-welcome'
    path: ./welcome/app/fe/bookinfo/manifests/manual
    targetRevision: argocd-workshop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # webhook:
  #   github:
  #     secret: webhook-secret
