apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configmap
data:
  dbname: {{.Values.database_prod.dbname}}
  dbtable: {{.Values.database_prod.dbtable}}
  image: {{.Values.pods.image}}:{{.Values.pods.tag}}
  food: {{.Values.food.drink|upper}}
  eat: {{.Values.food.eat|trunc 13}}

