#NOTE THAT THERE ARE ERRORS IN THE YML FILE FOR YOU TO FIX
version: '3' # Docker-compose yml version for docker compose builder
services: 
  web: 
   build: ./roles/web/
   depends_on:
     - db_mysql     
   ports: 
     - 8080:8080
   networks: # Define netwroks per service / role
     - db_layer
     
  db_mysql:
    image: wangxian/alpine-mysql
    environment: # env variables 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer
    volumes: 
      - logicalVoloume01:/app

# this will replace:  
 #docker run --rm -itd --network db_layer  --name db_mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=music -p 3306:3306 -v $(pwd):/app wangxian/alpine-mysql

networks: # custome configuration per network defined
 db_layer:
  driver: bridge
 app_layer:
  driver: bridge

volumes:
 logicalVoloume01:
 
