apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.databaseprod.dbname }}
  dbtable: {{ .Values.databaseprod.dbtable }}
  drink: {{ .Values.food.drink | upper }}
  eat: {{ .Values.food.eat | upper | trunc 13 | quote}}

