apiVersion: v1     
kind: Service      # Create new service
metadata:
  name: my-service # Name of the service
spec:
  selector:
    app: frontend    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http-web    # Setting multiple ports listterns 
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https-managment
    protocol: TCP
    port: 443
    targetPort: 9388


