name: List Repository Files

# Controls when the action will run
on:
  push:
    branches: [ "main", "develop" ]  # Runs when you push to these branches
  workflow_dispatch:              # Allows you to run this manually from the Actions tab

jobs:
  list-repo-contents:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repo onto the runner
      - name: Checkout Code
        uses: actions/actions/checkout@v4

      # Step 2: Run the shell command
      - name: List files with long format
        run: ls -l